language: node_js
node_js:
- '8'
install:
- npm install
cache:
  directories:
  - "./node_modules"
script:
- npm run test:no-watch
- npm run build:linux
- npm run bundle:css
- npm run cleanup
- npm run package
before_deploy:
- cd dist
deploy:
  provider: npm
  email: adel.mehrban@gmail.com
  api_key:
    secure: G1r/L+GyVbyer479Rmak0a7UovK5V2e4U5zhgXqg4rBXT66HuGxQiraJ1nkx44v8QhdSJVLl6O8Uohu3oyj7m2B9xZaNI1sWUe9ck7Ysk6w1mZju3LEg4aHoU7o2YpUnjpN3YsBLjWqHAtSNcNObiw/pU1mgjjJaCLhQUeD2CtjizZuhyh+83qx9HsQO+181eXFrqa95w3WTAP9Mn3S3wEB73CNyfHj21tBq4D9XAQeFyy5THPcWRBfjwo6tLkEszL6dGVE3MKgrRCf6cWyJlWnFVFpjqoblthr4E9fUJcz23lTZNVSfkbaBKuA33EII9hApJXK/d8gkE22/L3o3U/7qagV2j8v9kA+fs3A9rHip1USFg7iryfPngDB8R+qjw4m/zRa4LkN4Pr6Qw1oHBURpnDBCb0iOT1OBQx+mx7bAeoIqQzK9x5A/S4uAv6P3VtANbD7BMu8bBIK9ZZQRXweWYRFUIeDdWyrwEffYxiS77BbKwxiijQ71mGBdYoy2G2YE1or/YiDoc704tq6aCBfG+xIcW9Y34GnbNpJ8scUHwzqH2vtwFrZfWmqi2+Rwo8+A2WpVEKkT1DHvsi2qNb4EZWxZLs9IjF9HCEVlcTxFwXlqPpegBJft9EN3Pp3QjoLxRViETg4URgCXHIlvmnRkxkKx3FHPJLnmVn+B5Zo=
  on:
    repo: yashints/react-pass-strength
  skip_cleanup: true
